Repository Ameer2000Mzori/MonoText-Mern, pull requests merged in 2024-03, with the labels that each got.

#21 Destructure the backend files #20
  backend/src/controllers/articleController.js
  backend/src/controllers/userController.js
  backend/src/routes/articleRoute.js
  backend/src/routes/userRoute.js
  backend/src/server.js
Labels: enhancement, good first issue

#23 Connect backend to frontend so user can login #22
  backend/.env-example
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/controller.js
  backend/src/db/db.js
  backend/src/middlewares/token.js
  backend/src/modules/article.js
  backend/src/modules/rate.js
  backend/src/modules/users.js
  backend/src/routes/route.js
  backend/src/server.js
  backend/src/utils/hashing.js
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Navbar.jsx
  frontend/src/components/pages/Home/Home.jsx
  frontend/src/components/pages/Home/shared/LoginLinks.jsx
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/components/pages/LoginPage/LoginPage.jsx
  frontend/src/components/pages/LoginPage/hooks/LoginLogic.jsx
  next steps.png
Labels: enhancement

#25 fixed navbar problem
  frontend/src/components/Navbar.jsx
  frontend/src/components/NavbarMenu.jsx
Labels: bug

#29 Connect backend to user logged in dashbard #28
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/api/main.jsx
  frontend/src/components/pages/Home/Home.jsx
  frontend/src/components/pages/LoginPage/LoginPage.jsx
  frontend/src/components/pages/LoginPage/hooks/LoginLogic.jsx
  frontend/src/features/user/userSlice.js
  frontend/src/store/store.js
Labels: enhancement

#31 Convert normal forms into formik + using yup for validation #30
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/LoginPage/LoginPage.jsx
  frontend/src/components/pages/LoginPage/hooks/StyledComponents.jsx
Labels: enhancement

#33 Use formik and yup for the login page #32
  frontend/src/components/Navbar.jsx
  frontend/src/components/pages/LoginPage/LoginPage.jsx
  frontend/src/components/pages/LoginPage/hooks/ErrorMessage.jsx
  frontend/src/components/pages/LoginPage/hooks/StyledComponents.jsx
  frontend/src/components/shared/validationSchema.js
Labels: enhancement
